# Generated by Django 2.1.15 on 2023-05-02 05:22

from django.db import migrations


def insert_default_values(apps, schema):
    role = apps.get_model("core", "Role")
    roles = ['admin', 'employee']
    for rl in roles:
        rl_tmp = role(name_role=rl)
        rl_tmp.save()

    prod_type = apps.get_model("core", "ProductType")
    prods = ['peripheral', 'CPU', 'GPU', 'monitor', 'headphones', 'board', 'furniture', 'software', 'memory', 'cooling']
    for p in prods:
        prod_tmp = prod_type(name_product_type=p)
        prod_tmp.save()

    man = apps.get_model("core", "Manufacturer")
    mans = ['HP', 'ASUS', 'SAMSUNG', 'LG', 'SONY', 'VIEWSONIC', 'KINGSTONE', 'WD', 'LOGITECH', 'CORSAIR',
            'COOLER MASTER', 'LENOVO', 'ADATA', 'MSI', 'GIGABYTE']
    for idx, mn in enumerate(mans):
        mn_tmp = man(manufacturer_name=mn, manufacturer_nit=idx)
        mn_tmp.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [migrations.RunPython(insert_default_values)]
