# Generated by Django 2.1.15 on 2023-05-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_product',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
