# Generated by Django 2.1.15 on 2023-05-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_amount_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_ID', models.CharField(max_length=20)),
                ('client_surname', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(to='core.Product')),
            ],
        ),
    ]
